### PR TITLE
Adding scroll to prevent items in sublist from being cut off

### PR DESCRIPTION
**Pull request by ramirezg**

### CODE REVIEW

**Comment by ramirezg** [comment]
@mbland this would make the project we're working one much more usable, thoughts?

**Comment by mbland** [comment]
Can you include screenshots of before and after?

**Comment by ramirezg** [comment]
## Before - truncated list
screen shot 2015-10-21 at 2 37 52 pm
=
## After - scrolling list 
screen shot 2015-10-21 at 2 42 14 pm

**Comment by mbland** [comment]
_Sweeet_... Will cut a new gem now.

**Comment by mbland** [comment]
Pushed to v0.1.4 of [`guides_style_18f`](https://rubygems.org/gems/guides_style_18f). Thanks a bunch, @ramirezg!

**Comment by maya** [comment]
@mbland Wait why does the list need a vertical scroll. Shouldn't you just scroll down the page?

**Comment by mbland** [comment]
No, perhaps the scrollbar doesn't show it, but that's a pretty hard cut-off within the sidenav itself. Scrolling down the page doesn't work in this case.

**Comment by maya** [comment]
I guess I can't see the issue from the screenshot. If you could post of gif of the issue, I'd be able to see the issue fully.

**Pull request merged**
