### PR TITLE
Fix child nav expansion broken in #28

### PR DESCRIPTION
**Pull request by mbland**
Forgot that the sidebar depended on the `parent:` property. This fixes the problem by introducing the `guides_style_18f_nav_parent_url` tag that allows the template to compare this value against `link.url`.

cc: @ccostino @ertzeid @andrewmaier

### CODE REVIEW

**Comment by mbland** [comment]
Actually updated this to replace `guides_style_18f_nav_parent_url` with `guides_style_18f_should_expand_nav`. On top of that, this PR now also implements arbitrarily deep sidebar nesting. Requires a couple of plugins, given the limitations of the basic Liquid template syntax. A style update may perhaps be in order.

**Comment by mbland** [comment]
Ping... Any takers?

**Comment by ccostino** [comment]
I just took a look, everything appears fine to me!  Merging.

**Comment by mbland** [comment]
Thanks, @ccostino!

**Pull request merged**
