### PR TITLE
Integrate us_web_design_standards

### PR DESCRIPTION
**Pull request by mbland**
This is just the first step. The dependency is in the gemspec, the generator and sass modules depend on us_web_design_standards to integrate that gem's generator and sass modules, and the guides_style_18f.scss file imports the us_web_design_standards styles.

However, this initial commit does not update the layouts, includes, and styles to use the us_web_design_standards styles.

@maya and @msecret: Here's how you can work on this branch to integrate the design standards styles while testing with 18F/guides-template. First, clone both repos, making sure to clone 18F/guides-style with this PR's branch:

``` sh
$ git clone git@github.com:18F/guides-style --branch uswds
$ git clone git@github.com:18F/guides-template
$ cd guides-template
```

Then update the `guides_style_18f` line of the guides-template `Gemfile` to:

``` ruby
gem 'guides_style_18f', path: '../guides-style'
```

Then run the following to update the `Gemfile.lock` and run the site locally:

``` sh
$ bundle install
$ ./go serve
```

Now, you'll want to change directories back to `../guides-style`, and update the layouts, includes, and styles in there. You'll find them all under `lib/guides_style_18f` in the `layouts`, `includes`, and `sass` directories, respectively. Do anything and everything you feel you need to do to those files.

Don't hesitate to ping me if you have any questions!

### CODE REVIEW

**Comment by mbland** [comment]
Oh right, the repo for the new [`us_web_design_standards` gem](https://rubygems.org/gems/us_web_design_standards) is [18F/us_web_design_standards_gem](https://github.com/18F/us_web_design_standards_gem).

**Comment by maya** [comment]
Thanks @mbland! So do we want to essentially remove the current styles in `_guides_style_18f_custom.scss` and `_guides_style_18f_custom.scss`?

**Comment by maya** [comment]
Also, don't we want to update the template? so in the directory `guides-template`? Also, where is the template located?

**Comment by mbland** [comment]
@maya Yeah, it may well be that all those other styles should get stripped out, or those styles should become aliases of those in the web design standards.

Most of the templates are actually in the `layouts`, `includes`, and `sass` subdirectories of `lib/guides_style_18f` in this repo. This gem is what allows most other Guides to not have to have any templates themselves, including 18F/guides-template.

**Comment by mbland** [comment]
cc: @vz3

**Pull request closed without merging**
