### PR TITLE
convert to a gem-based theme

### LINKED ISSUE #73: consider converting to a Jekyll Theme
Will likely make the project simpler, though this requires Jekyll 3.2+.

https://jekyllrb.com/docs/themes/

### PR DESCRIPTION
**Pull request by afeld**
Closes #73.

This fixes the theme to work for Jekyll 3.2+, and is easier to override. Was able to cut out a lot of custom logic that the gem-based themes now handle built-in to Jekyll.

https://jekyllrb.com/docs/themes/#creating-a-gem-based-theme

### CODE REVIEW

**Comment by afeld** [comment]
Tested with several sites locally. Only change required is adding `theme: guides_style_18f` in `_config.yml`, and using `default` instead of `guides_style_18f_default` for the layout.

screen shot 2017-10-26 at 4 10 00 pm

**Comment by adborden** [comment]
This looks great! I tried it out with the [partnership playbook](https://github.com/18F/partnership-playbook/tree/adb-guides-style-jekyll-3.2) and everything works except the assets. The CSS is there, but all the assets are missing from `_site`.

**Comment by adborden** [comment]
... also some test errors when running `./go build` https://gist.github.com/adborden/3a12488c3c156ccfd712562a24eaa5d1

**Comment by afeld** [comment]
@adborden Thanks for checking it out! Fixed the asset problem in 71786a5, and fixed the build in #111.

**Comment by jeremiak** [comment]
Just tried this out on the Handbook site and it works well. This PR looks good to me!

**Pull request merged**
