### PR TITLE
Remove anchor js

### PR DESCRIPTION
**Pull request by nickbristow**
Anchor js was causing some accessibility issues.

### CODE REVIEW

**Comment by nickbristow** [comment]
@ertzeid

**Comment by afeld** [comment]
@nickbristow Anchor links are super useful, and I miss not having them...is there a way to do them in an accessible way?

**Comment by nickbristow** [comment]
@afeld oh totally. The thing we were using just implemented them in an inaccessible way.

**Comment by afeld** [comment]
Can you elaborate about what would need to be done to make them accessible?

**Comment by nickbristow** [comment]
@afeld The links created by the script need to have content (current content is added via CSS content).  Just some text that says what anchor its point at is. (The text can be hidden) 

I think at the time, I spent a little time trying to get this work, but the styles weren't cooperating. It was easier at the time to pull it out for the time being as no one had time to fix it.

**Pull request merged**
