### PR TITLE
[WIP] Add jekyll_pages_api{,_search}

### PR DESCRIPTION
**Pull request by mbland**
https://github.com/18F/jekyll_pages_api/
https://github.com/18F/jekyll_pages_api_search/

cc: @andrewmaier

### CODE REVIEW

**Comment by mbland** [comment]
Don't forget to add the `jekyll_pages_api_search:` config to `_config.yml` in your local 18F/guides-template repo per: https://github.com/18F/jekyll_pages_api_search/#installation

**Comment by mbland** [comment]
Here's what the integration looks like for starters. It's fully functional, just not styled in an optimal fashion:

guides-search

**Comment by andrewmaier** [comment]
I've got some ideas here. Mainly I think we can do an iteration on the new Hub design.

**Comment by mbland** [comment]
That's out of scope for this PR. This PR just needs a proper style and placement for the widget. Think of this exercise as a means of gaining insight into the larger problem, but _finish solving this one first_. Wax on, wax off.

**Comment by andrewmaier** [comment]
@mbland Pushed!

**Comment by mbland** [comment]
Beautimus! Will merge and release as `guides_style_18f` v0.3.0.

For the record, this is what it looks like now:

guides-search-finished

**Comment by afeld** [comment]
YESSS YOU READ MY MIND EXCEPT IN THE FUTURE :clap:

**Pull request merged**
